name: Deploy to Github Pages

on:
  push

env:
  NODE_VERSION: 18.x
  NODE_ENV: "production"
  OUTPUT_DIR: dist
  ARTIFACT_NAME: compiled_assets

jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Install Gulp CLI
        run: npm install --global gulp-cli
      - name: Run Build Task
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_DIR }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.ARTIFACT_NAME }}