name: Github Pages Deployment

on:
  push:
    branches: [ "master", "main" ]

env:
  PRODUCTION: true
  NODE_VERSION: 18.x
  OUTPUT_DIR: dist
  INSTALL_COMMAND: npm install
  BUILD_COMMAND: npm run build
  ARTIFACT_NAME: compiled_assets

jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: ${{ env.INSTALL_COMMAND }}
      - name: Run Build Task
        run: ${{ env.BUILD_COMMAND }}
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_DIR }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: ${{ env.ARTIFACT_NAME }}